name: "Maximize Build Space"
description: "Remove large artifacts to maximize available build space on GitHub Actions runners."
runs:
  using: "composite"
  steps:
    - name: Clean
      shell: bash
      run: |
        echo "Available storage before:"
        sudo df -h
        echo

        echo "Removing Removes .NET runtime and libraries..."
        sudo rm -rf /usr/share/dotnet

        echo "Removing Android SDKs and Tools..."
        sudo rm -rf /usr/local/lib/android

        echo "Removing GHC (Haskell) artifacts..."
        sudo rm -rf /opt/ghc

        echo "Removing CodeQL Action Bundles..."
        sudo rm -rf /opt/hostedtoolcache/CodeQL

        echo "Removing cached Docker images..."
        sudo docker image prune --all --force

        echo "Available storage after:"
        sudo df -h
        echo
