---

name: CI

on:
  pull_request:
    paths:
      - io.elementary.Sdk.json

    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    name: Build (${{ matrix.configuration.name }})
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        configuration:
          - name: x86
            platform: false
            architecture: x86_64

          - name: ARM
            platform: arm64
            architecture: aarch64

    steps:
      - name: Clean
        uses: easimon/maximize-build-space@v9
        with:
          # Reserve some space on the / partition to install the needed org.gnome runtimes and their Debug extensions.
          # This probably needs around 10-12GB, the rest of the free space on / then gets assigned to the build directory
          # where we need the most space
          root-reserve-mb: 16000
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          sudo apt update
          sudo apt install -y ccache flatpak flatpak-builder meson xvfb zstd
          sudo rm -rf /var/lib/{apt,dpkg,cache,log}/

          sudo flatpak remote-add --system --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        if: ${{ matrix.configuration.platform }}
        with:
          platforms: ${{ matrix.configuration.platform }}

      - name: Build
        env:
          DISPLAY: "0:0"
        run: |
          meson setup build --cross-file="architectures/${{ matrix.configuration.architecture }}.crossfile"
          sudo xvfb-run --auto-servernum flatpak-builder --arch=${{ matrix.configuration.architecture }} --disable-rofiles-fuse --keep-build-dirs --install-deps-from=flathub --ccache --repo=elementary builddir ./build/io.elementary.Sdk.json

      - name: Fix Permissions
        run: sudo chown -R runner:docker .
